In [1]:
import pandas as pd
from ast import literal_eval
import numpy as np

In [2]:
df = pd.read_csv("/mnt/data/Users/A-PROOF/Cecilia_S/keyword_matches_notes/all_sents_small3.csv")

In [3]:
df.groupby('pred_domains').count()

                             Unnamed: 0    text  confidence
pred_domains
[0, 0, 0, 0, 0, 0, 0, 0, 0]      372797  372797      372797
[0, 0, 0, 0, 0, 0, 0, 0, 1]        8169    8169        8169
[0, 0, 0, 0, 0, 0, 0, 1, 0]        2116    2116        2116
[0, 0, 0, 0, 0, 0, 0, 1, 1]          11      11          11
[0, 0, 0, 0, 0, 0, 1, 0, 0]        2268    2268        2268
[0, 0, 0, 0, 0, 0, 1, 1, 0]           6       6           6
[0, 0, 0, 0, 0, 1, 0, 0, 0]        4019    4019        4019
[0, 0, 0, 0, 0, 1, 0, 0, 1]          29      29          29
[0, 0, 0, 0, 0, 1, 0, 1, 0]           1       1           1
[0, 0, 0, 0, 0, 1, 1, 0, 0]         280     280         280
[0, 0, 0, 0, 1, 0, 0, 0, 0]        3561    3561        3561
[0, 0, 0, 0, 1, 0, 0, 0, 1]           3       3           3
[0, 0, 0, 0, 1, 0, 0, 1, 0]         232     232         232
[0, 0, 0, 1, 0, 0, 0, 0, 0]        2125    2125        2125
[0, 0, 0, 1, 0, 0, 0, 0, 1]           5       5           5
[0, 0, 0, 1, 0, 0, 0, 1, 0]          14      14          14
[0, 0, 0, 1, 0, 0, 1, 0, 0]         108     108         108
[0, 0, 0, 1, 0, 0, 1, 1, 0]           7       7           7
[0, 0, 0, 1, 0, 1, 1, 0, 0]           3       3           3
[0, 0, 0, 1, 1, 0, 0, 0, 0]          11      11          11
[0, 0, 1, 0, 0, 0, 0, 0, 0]        1342    1342        1342
[0, 0, 1, 0, 0, 0, 0, 0, 1]           1       1           1
[0, 0, 1, 0, 0, 0, 1, 0, 0]           4       4           4
[0, 0, 1, 0, 0, 0, 1, 0, 1]           3       3           3
[0, 1, 0, 0, 0, 0, 0, 0, 0]         458     458         458
[0, 1, 0, 0, 0, 0, 0, 0, 1]           2       2           2
[0, 1, 0, 1, 0, 0, 0, 0, 0]          11      11          11
[1, 0, 0, 0, 0, 0, 0, 0, 0]        7094    7094        7094
[1, 0, 0, 0, 0, 0, 0, 0, 1]          16      16          16
[1, 0, 0, 0, 0, 0, 0, 1, 0]          10      10          10
[1, 0, 0, 0, 0, 0, 1, 0, 0]         156     156         156
[1, 0, 0, 0, 0, 1, 0, 0, 0]           7       7           7
[1, 0, 0, 0, 0, 1, 1, 0, 0]          11      11          11
[1, 0, 0, 0, 1, 0, 0, 0, 0]          25      25          25
[1, 0, 0, 0, 1, 0, 0, 1, 0]           3       3           3
[1, 0, 0, 1, 0, 0, 0, 0, 0]          88      88          88
[1, 0, 0, 1, 0, 0, 1, 0, 0]           4       4           4

In [4]:
df['confidence'] = df.confidence.map(lambda x: literal_eval(x))

In [5]:
df['pred_domains'] = df.pred_domains.map(lambda x: literal_eval(x))

In [6]:
df

,Unnamed: 0,text,pred_domains,confidence
0,0,CAD herplaatst 3)Verhoogde infectieparameters ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112584363307856, 0.11109968732674443, 0.1..."
1,1,Volgens partner toen wel wat lastiger te verst...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11099488399024844, 0.11125417776010532, 0.1..."
2,2,"Trachplaatsing , ongecompliceerd Addendum 10-0...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11121484760587265, 0.11108786953667825, 0.1..."
3,3,In uw familie komt de erfelijke hartziekte bru...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112231922728447, 0.11110214515195024, 0.1..."
4,4,T2N1 mondbodemcarcinoom essentiële hypertensie...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112595752961708, 0.11110058361628154, 0.1..."
...,...,...,...,...
404995,404995,"Maatschappelijk werk is icc , komt vanmiddag n...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10793136055337005, 0.1079772966568992, 0.13..."
404996,404996,Eerder beschreven afwijkingen op X-thorax zijn...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112841692176009, 0.11109890649526585, 0.1..."
404997,404997,"Betreft : A. v Ingen-Stuut , geb. 15-10-1922 ,...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112734193415448, 0.11109958630884038, 0.1..."
404998,404998,Inhoudelijk gepreoccupeerd met de beperkte ste...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.110885243764016, 0.11093028572989504, 0.110..."
404999,404999,Patiënt nam dit medicijn voorheen in om in sla...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11109901406417347, 0.11110197366676834, 0.1..."

In [7]:
confidence_scores = df.confidence.tolist()
predictions = df.pred_domains.tolist()

In [8]:
df[['adm', 'att', 'ber', 'enr', 'etn', 'fac', 'ins', 'mbw', 'stm']] = pd.DataFrame(df.pred_domains.tolist(), index =df.index)
df[['adm_cs', 'att_cs', 'ber_cs', 'enr_cs', 'etn_cs', 'fac_cs', 'ins_cs', 'mbw_cs', 'stm_cs']] = pd.DataFrame(df.confidence.tolist(), index =df.index)

In [9]:
pd.set_option('display.max_columns', None)

In [10]:
df

,Unnamed: 0,text,pred_domains,confidence,adm,att,ber,enr,etn,fac,ins,mbw,stm,adm_cs,att_cs,ber_cs,enr_cs,etn_cs,fac_cs,ins_cs,mbw_cs,stm_cs
0,0,CAD herplaatst 3)Verhoogde infectieparameters ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112584363307856, 0.11109968732674443, 0.1...",0,0,0,0,0,0,0,0,0,0.111126,0.111100,0.111102,0.111102,0.111124,0.111119,0.111116,0.111103,0.111110
1,1,Volgens partner toen wel wat lastiger te verst...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11099488399024844, 0.11125417776010532, 0.1...",0,0,0,0,0,0,0,0,0,0.110995,0.111254,0.111032,0.111002,0.110986,0.111074,0.111031,0.110972,0.111654
2,2,"Trachplaatsing , ongecompliceerd Addendum 10-0...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11121484760587265, 0.11108786953667825, 0.1...",0,0,0,0,0,0,0,0,0,0.111215,0.111088,0.111089,0.111090,0.111113,0.111106,0.111107,0.111091,0.111102
3,3,In uw familie komt de erfelijke hartziekte bru...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112231922728447, 0.11110214515195024, 0.1...",0,0,0,0,0,0,0,0,0,0.111122,0.111102,0.111108,0.111103,0.111115,0.111115,0.111114,0.111104,0.111117
4,4,T2N1 mondbodemcarcinoom essentiële hypertensie...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112595752961708, 0.11110058361628154, 0.1...",0,0,0,0,0,0,0,0,0,0.111126,0.111101,0.111104,0.111102,0.111120,0.111120,0.111113,0.111105,0.111110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404995,404995,"Maatschappelijk werk is icc , komt vanmiddag n...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10793136055337005, 0.1079772966568992, 0.13...",0,0,0,0,0,0,0,0,0,0.107931,0.107977,0.135665,0.107974,0.107947,0.107963,0.108205,0.107936,0.108401
404996,404996,Eerder beschreven afwijkingen op X-thorax zijn...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112841692176009, 0.11109890649526585, 0.1...",0,0,0,0,0,0,0,0,0,0.111128,0.111099,0.111101,0.111101,0.111103,0.111126,0.111120,0.111097,0.111125
404997,404997,"Betreft : A. v Ingen-Stuut , geb. 15-10-1922 ,...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11112734193415448, 0.11109958630884038, 0.1...",0,0,0,0,0,0,0,0,0,0.111127,0.111100,0.111108,0.111101,0.111111,0.111112,0.111112,0.111103,0.111126
404998,404998,Inhoudelijk gepreoccupeerd met de beperkte ste...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.110885243764016, 0.11093028572989504, 0.110...",0,0,0,0,0,0,0,0,0,0.110885,0.110930,0.110953,0.110900,0.110884,0.111197,0.111281,0.110865,0.112104
404999,404999,Patiënt nam dit medicijn voorheen in om in sla...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.11109901406417347, 0.11110197366676834, 0.1...",0,0,0,0,0,0,0,0,0,0.111099,0.111102,0.110995,0.111056,0.110974,0.110999,0.111198,0.110962,0.111615

In [11]:
df_hq = df

In [12]:
df_lq = df

In [13]:
conditions = [(df_hq['adm'] == 0) & (df_hq['att'] == 0) & (df_hq['ber'] == 0) & (df_hq['enr'] == 0) & (df_hq['etn'] == 0) & (df_hq['fac'] == 0) & (df_hq['ins'] == 0) & (df_hq['mbw'] == 0) & (df_hq['stm'] == 0)]
choices = ['none']
df_hq['quality'] = np.select(conditions, choices, default='hq')

In [14]:
df_hq.groupby('quality').count()

,Unnamed: 0,text,pred_domains,confidence,adm,att,ber,enr,etn,fac,ins,mbw,stm,adm_cs,att_cs,ber_cs,enr_cs,etn_cs,fac_cs,ins_cs,mbw_cs,stm_cs
quality,,,,,,,,,,,,,,,,,,,,,,
hq,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203,32203
none,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797,372797

In [15]:
hq1 = df_hq[df_hq['quality']=='hq']

In [16]:
hq = hq1[['text', 'pred_domains']]

In [17]:
hq.rename(columns={'pred_domains':'labels'}, inplace=True)

/tmp/ipykernel_529503/643907805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hq.rename(columns={'pred_domains':'labels'}, inplace=True)

In [18]:
hq

,text,labels
17,"Reactie op rituximab ( tachypneu , dyspneu en ...","[1, 0, 0, 0, 0, 0, 0, 0, 0]"
25,Moeder geeft aan dat Wail minder eetlust heeft...,"[0, 0, 0, 0, 0, 0, 0, 1, 0]"
26,Hierbij nog altijd wisselend een tachydyspneu ...,"[1, 0, 0, 0, 0, 0, 0, 0, 0]"
34,"Mw zegt de snelle hartslag wel te voelen , maa...","[1, 0, 0, 0, 0, 0, 0, 0, 0]"
39,"CVID-19 positief ( 13-9 ) met milde klachten ,...","[1, 0, 0, 0, 0, 0, 0, 0, 0]"
...,...,...
404966,Rond 00.30 uur is Niko langs de trap naar het ...,"[0, 0, 0, 0, 0, 1, 0, 0, 0]"
404974,"Niet pijnlijk , was eenmaal benauwd waarvoor p...","[1, 0, 0, 0, 0, 0, 0, 0, 0]"
404979,"Tractus circulatorius : geen bijzonderheden , ...","[0, 0, 0, 1, 0, 0, 0, 0, 0]"
404985,Geen sport Knielt op de knieën voor bidden : m...,"[0, 0, 0, 0, 0, 0, 1, 0, 0]"
404986,Wel nog bij lopen onzeker wat zij duizelig noe...,"[0, 0, 0, 0, 0, 1, 0, 0, 0]"

In [19]:
conditions = [(df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['adm_cs'] >= 0.12) & (df_lq['adm_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['att_cs'] >= 0.12) & (df_lq['att_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['ber_cs'] >= 0.12) & (df_lq['ber_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['enr_cs'] >= 0.12) & (df_lq['enr_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['etn_cs'] >= 0.12) & (df_lq['etn_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['fac_cs'] >= 0.12) & (df_lq['fac_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['ins_cs'] >= 0.12) & (df_lq['ins_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['mbw_cs'] >= 0.12) & (df_lq['mbw_cs'] < 0.15),
              (df_lq['adm'] == 0) & (df_lq['att'] == 0) & (df_lq['ber'] == 0) & (df_lq['enr'] == 0) & (df_lq['etn'] == 0) & (df_lq['fac'] == 0) & (df_lq['ins'] == 0) & (df_lq['mbw'] == 0) & (df_lq['stm'] == 0) & (df_lq['stm_cs'] >= 0.12) & (df_lq['stm_cs'] < 0.15)
             ]
choices = ['lq', 'lq', 'lq', 'lq', 'lq', 'lq', 'lq', 'lq', 'lq']
df_lq['quality'] = np.select(conditions, choices, default='')

In [20]:
df_lq.groupby('quality').count()

,Unnamed: 0,text,pred_domains,confidence,adm,att,ber,enr,etn,fac,ins,mbw,stm,adm_cs,att_cs,ber_cs,enr_cs,etn_cs,fac_cs,ins_cs,mbw_cs,stm_cs
quality,,,,,,,,,,,,,,,,,,,,,,
,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118,379118
lq,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882,25882

In [21]:
lq1 = df_lq[df_lq['quality']=='lq']

In [22]:
lq1

,Unnamed: 0,text,pred_domains,confidence,adm,att,ber,enr,etn,fac,ins,mbw,stm,adm_cs,att_cs,ber_cs,enr_cs,etn_cs,fac_cs,ins_cs,mbw_cs,stm_cs,quality
22,22,"Lichamelijk onderzoek : Niet ziek , alert , bl...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.121533752277026, 0.10969307586705888, 0.109...",0,0,0,0,0,0,0,0,0,0.121534,0.109693,0.109369,0.110283,0.109495,0.109373,0.109460,0.109385,0.111408,lq
31,31,Conclusie 10 jarige jongen met status na volle...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10699566577030171, 0.10687673161162758, 0.1...",0,0,0,0,0,0,0,0,0,0.106996,0.106877,0.106878,0.106921,0.143659,0.106928,0.106935,0.107901,0.106905,lq
57,57,"Kan 1 keer per week zijn , of meerdere keren p...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10942423780714891, 0.1095235157379629, 0.11...",0,0,0,0,0,0,0,0,0,0.109424,0.109524,0.111882,0.109662,0.109468,0.110685,0.120134,0.109422,0.109799,lq
62,62,"0,21 , regelmatig centrale incidenten , wv Fi2...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.1481281782726791, 0.1064284303727127, 0.106...",0,0,0,0,0,0,0,0,0,0.148128,0.106428,0.106421,0.106455,0.106558,0.106445,0.106592,0.106454,0.106519,lq
118,118,Kort daarop kwam de contactpersoon voor de twe...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.1087018243721664, 0.10869280877536001, 0.11...",0,0,0,0,0,0,0,0,0,0.108702,0.108693,0.110090,0.108883,0.108810,0.110480,0.126083,0.108793,0.109468,lq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404930,404930,Heeft hulp in de huishouding en fysiotherapie ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.1095031089343702, 0.1094929841567385, 0.109...",0,0,0,0,0,0,0,0,0,0.109503,0.109493,0.109677,0.109532,0.109539,0.111770,0.121319,0.109479,0.109688,lq
404978,404978,Zegt dat hij ' niet zo goed tegen handicaps ka...,"[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10927548909196745, 0.10964653674381757, 0.1...",0,0,0,0,0,0,0,0,0,0.109275,0.109647,0.109245,0.109566,0.109200,0.109283,0.109409,0.109163,0.125212,lq
404981,404981,"Met Tineke gesproken over vorige gesprek , is ...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10991203320024887, 0.10992349127369141, 0.1...",0,0,0,0,0,0,0,0,0,0.109912,0.109923,0.109884,0.109913,0.109902,0.109890,0.109899,0.109857,0.120819,lq
404983,404983,"Geen verhoogd suicidaliteitsrisico , geen acti...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10739775314416149, 0.10736165720050829, 0.1...",0,0,0,0,0,0,0,0,0,0.107398,0.107362,0.107352,0.107347,0.107381,0.107319,0.107348,0.107310,0.141183,lq
404995,404995,"Maatschappelijk werk is icc , komt vanmiddag n...","[0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.10793136055337005, 0.1079772966568992, 0.13...",0,0,0,0,0,0,0,0,0,0.107931,0.107977,0.135665,0.107974,0.107947,0.107963,0.108205,0.107936,0.108401,lq

In [23]:
for ri, row in lq1.iterrows():
    for score in row['confidence']:
        if score >= 0.12:
            index = row['confidence'].index(score)
            row['pred_domains'][index] = 1

In [24]:
lq1

,Unnamed: 0,text,pred_domains,confidence,adm,att,ber,enr,etn,fac,ins,mbw,stm,adm_cs,att_cs,ber_cs,enr_cs,etn_cs,fac_cs,ins_cs,mbw_cs,stm_cs,quality
22,22,"Lichamelijk onderzoek : Niet ziek , alert , bl...","[1, 0, 0, 0, 0, 0, 0, 0, 0]","[0.121533752277026, 0.10969307586705888, 0.109...",0,0,0,0,0,0,0,0,0,0.121534,0.109693,0.109369,0.110283,0.109495,0.109373,0.109460,0.109385,0.111408,lq
31,31,Conclusie 10 jarige jongen met status na volle...,"[0, 0, 0, 0, 1, 0, 0, 0, 0]","[0.10699566577030171, 0.10687673161162758, 0.1...",0,0,0,0,0,0,0,0,0,0.106996,0.106877,0.106878,0.106921,0.143659,0.106928,0.106935,0.107901,0.106905,lq
57,57,"Kan 1 keer per week zijn , of meerdere keren p...","[0, 0, 0, 0, 0, 0, 1, 0, 0]","[0.10942423780714891, 0.1095235157379629, 0.11...",0,0,0,0,0,0,0,0,0,0.109424,0.109524,0.111882,0.109662,0.109468,0.110685,0.120134,0.109422,0.109799,lq
62,62,"0,21 , regelmatig centrale incidenten , wv Fi2...","[1, 0, 0, 0, 0, 0, 0, 0, 0]","[0.1481281782726791, 0.1064284303727127, 0.106...",0,0,0,0,0,0,0,0,0,0.148128,0.106428,0.106421,0.106455,0.106558,0.106445,0.106592,0.106454,0.106519,lq
118,118,Kort daarop kwam de contactpersoon voor de twe...,"[0, 0, 0, 0, 0, 0, 1, 0, 0]","[0.1087018243721664, 0.10869280877536001, 0.11...",0,0,0,0,0,0,0,0,0,0.108702,0.108693,0.110090,0.108883,0.108810,0.110480,0.126083,0.108793,0.109468,lq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404930,404930,Heeft hulp in de huishouding en fysiotherapie ...,"[0, 0, 0, 0, 0, 0, 1, 0, 0]","[0.1095031089343702, 0.1094929841567385, 0.109...",0,0,0,0,0,0,0,0,0,0.109503,0.109493,0.109677,0.109532,0.109539,0.111770,0.121319,0.109479,0.109688,lq
404978,404978,Zegt dat hij ' niet zo goed tegen handicaps ka...,"[0, 0, 0, 0, 0, 0, 0, 0, 1]","[0.10927548909196745, 0.10964653674381757, 0.1...",0,0,0,0,0,0,0,0,0,0.109275,0.109647,0.109245,0.109566,0.109200,0.109283,0.109409,0.109163,0.125212,lq
404981,404981,"Met Tineke gesproken over vorige gesprek , is ...","[0, 0, 0, 0, 0, 0, 0, 0, 1]","[0.10991203320024887, 0.10992349127369141, 0.1...",0,0,0,0,0,0,0,0,0,0.109912,0.109923,0.109884,0.109913,0.109902,0.109890,0.109899,0.109857,0.120819,lq
404983,404983,"Geen verhoogd suicidaliteitsrisico , geen acti...","[0, 0, 0, 0, 0, 0, 0, 0, 1]","[0.10739775314416149, 0.10736165720050829, 0.1...",0,0,0,0,0,0,0,0,0,0.107398,0.107362,0.107352,0.107347,0.107381,0.107319,0.107348,0.107310,0.141183,lq
404995,404995,"Maatschappelijk werk is icc , komt vanmiddag n...","[0, 0, 1, 0, 0, 0, 0, 0, 0]","[0.10793136055337005, 0.1079772966568992, 0.13...",0,0,0,0,0,0,0,0,0,0.107931,0.107977,0.135665,0.107974,0.107947,0.107963,0.108205,0.107936,0.108401,lq

In [25]:
lq = lq1[['text', 'pred_domains']]

In [26]:
lq.rename(columns={'pred_domains':'labels'}, inplace=True)

/tmp/ipykernel_529503/780572136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lq.rename(columns={'pred_domains':'labels'}, inplace=True)

In [27]:
lq

,text,labels
22,"Lichamelijk onderzoek : Niet ziek , alert , bl...","[1, 0, 0, 0, 0, 0, 0, 0, 0]"
31,Conclusie 10 jarige jongen met status na volle...,"[0, 0, 0, 0, 1, 0, 0, 0, 0]"
57,"Kan 1 keer per week zijn , of meerdere keren p...","[0, 0, 0, 0, 0, 0, 1, 0, 0]"
62,"0,21 , regelmatig centrale incidenten , wv Fi2...","[1, 0, 0, 0, 0, 0, 0, 0, 0]"
118,Kort daarop kwam de contactpersoon voor de twe...,"[0, 0, 0, 0, 0, 0, 1, 0, 0]"
...,...,...
404930,Heeft hulp in de huishouding en fysiotherapie ...,"[0, 0, 0, 0, 0, 0, 1, 0, 0]"
404978,Zegt dat hij ' niet zo goed tegen handicaps ka...,"[0, 0, 0, 0, 0, 0, 0, 0, 1]"
404981,"Met Tineke gesproken over vorige gesprek , is ...","[0, 0, 0, 0, 0, 0, 0, 0, 1]"
404983,"Geen verhoogd suicidaliteitsrisico , geen acti...","[0, 0, 0, 0, 0, 0, 0, 0, 1]"
404995,"Maatschappelijk werk is icc , komt vanmiddag n...","[0, 0, 1, 0, 0, 0, 0, 0, 0]"

x = df[df['adm'] == 1]

y = x[['text', 'pred_domains']]

y

In [28]:
hq_onethird = int(len(hq)/3)

In [29]:
lq_onethird = int(len(lq)/3)

In [30]:
hq_data1 = hq.iloc[:hq_onethird]

In [31]:
len(hq_data1)

10734

In [32]:
hq_data2 = hq.iloc[hq_onethird:hq_onethird*2]

In [33]:
len(hq_data2)

10734

In [34]:
hq_data3 = hq.iloc[hq_onethird*2:]

In [35]:
len(hq_data3)

10735

In [36]:
lq_data1 = lq.iloc[:lq_onethird]

In [37]:
len(lq_data1)

8627

In [38]:
lq_data2 = lq.iloc[lq_onethird:lq_onethird*2]

In [39]:
len(lq_data2)

8627

In [40]:
lq_data3 = lq.iloc[lq_onethird*2:]

In [41]:
len(lq_data3)

8628

In [42]:
hq_data1.to_csv("/extradisk/data/cecilia_s/a-proof-zonmw/data/hq_data1_2.csv", index=False)

In [43]:
hq_data2.to_csv("/extradisk/data/cecilia_s/a-proof-zonmw/data/hq_data2_2.csv", index=False)

In [44]:
hq_data3.to_csv("/extradisk/data/cecilia_s/a-proof-zonmw/data/hq_data3_2.csv", index=False)

In [45]:
lq_data1.to_csv("/extradisk/data/cecilia_s/a-proof-zonmw/data/lq_data1_2.csv", index=False)

In [46]:
lq_data2.to_csv("/extradisk/data/cecilia_s/a-proof-zonmw/data/lq_data2_2.csv", index=False)

In [47]:
lq_data3.to_csv("/extradisk/data/cecilia_s/a-proof-zonmw/data/lq_data3_2.csv", index=False)